### ISSUE TITLE
Could you create a new tag for version 1.2.1

### ISSUE THREAD

**Issue by bjoern-flagbit** [runelaenen/sw6-redirects#5]
Because composer.json in main branch looks more correct.
Just the new tag is missing. Thx.

**Comment by runelaenen** [comment]
Hi @bjoern-flagbit 
A new version 1.3.0 had been added.

**Comment by runelaenen** [comment]
But fyi, this functionality is available in the core shopware. So you don't need this plugin anymore.

**Comment by bjoern-flagbit** [comment]
What? Did I missed this. :scream: 

Checked in 6.4.7.0 Version and did not see some admin part where you can see the 301 redirects. :confused: 

Thx anyway.

**Comment by runelaenen** [comment]
Ah yeah, you are right. I'm sorry, I was confused. I thought this issue was on https://github.com/runelaenen/sw6-category-links :D
